#ifndef __RDEVICEERHANDCANCMD_H__
#define __RDEVICEERHANDCANCMD_H__

#define CAN_CMD_BASE				(0x0000)

#define CAN_CMD_ENABLE			(0x01 + CAN_CMD_BASE)
#define CAN_CMD_DISABLE			(0x02 + CAN_CMD_BASE)
#define CAN_CMD_INIT_SYS			(0x03 + CAN_CMD_BASE)
#define CAN_CMD_RESET_ENC		(0x04 + CAN_CMD_BASE)
#define CAN_CMD_MOTOR_ON			(0x05 + CAN_CMD_BASE)
#define CAN_CMD_MOTOR_OFF		(0x06 + CAN_CMD_BASE)
#define CAN_CMD_REQ_SEND_POS		(0x07 + CAN_CMD_BASE)
#define CAN_CMD_CANCEL_SEND_POS	(0x08 + CAN_CMD_BASE)
#define CAN_CMD_SET_PROP			(0x09 + CAN_CMD_BASE)
#define CAN_CMD_GET_PROP			(0x0A + CAN_CMD_BASE)
#define CAN_CMD_UPDATE_READ		(0x0B + CAN_CMD_BASE)
#define CAN_CMD_UPDATE_WRITE		(0x0C + CAN_CMD_BASE)

#endif // __RDEVICEERHANDCANCMD_H__
